import { Campaign } from '@/types';

export const mockCampaigns: Campaign[] = [
  {
    id: '1',
    name: 'Black Friday 2024',
    type: 'email',
    status: 'active',
    reach: 15420,
    clicks: 2341,
    conversions: 187,
    createdAt: new Date('2024-09-15'),
  },
  {
    id: '2',
    name: 'Nuevo iPhone 15 - WhatsApp',
    type: 'whatsapp',
    status: 'completed',
    reach: 8750,
    clicks: 1876,
    conversions: 94,
    createdAt: new Date('2024-09-10'),
  },
  {
    id: '3',
    name: 'Descuento Estudiantes',
    type: 'in-web',
    status: 'active',
    reach: 3421,
    clicks: 567,
    conversions: 78,
    createdAt: new Date('2024-09-20'),
  },
  {
    id: '4',
    name: 'SMS Back to School',
    type: 'sms',
    status: 'paused',
    reach: 12300,
    clicks: 1890,
    conversions: 145,
    createdAt: new Date('2024-08-25'),
  },
  {
    id: '5',
    name: 'Newsletter Semanal',
    type: 'email',
    status: 'active',
    reach: 25600,
    clicks: 3200,
    conversions: 256,
    createdAt: new Date('2024-01-01'),
  },
  {
    id: '6',
    name: 'Promoción Gaming',
    type: 'whatsapp',
    status: 'draft',
    reach: 0,
    clicks: 0,
    conversions: 0,
    createdAt: new Date('2024-09-22'),
  },
  {
    id: '7',
    name: 'Pop-up Descuento 10%',
    type: 'in-web',
    status: 'active',
    reach: 18450,
    clicks: 2876,
    conversions: 432,
    createdAt: new Date('2024-08-15'),
  },
  {
    id: '8',
    name: 'Reactivación Clientes',
    type: 'email',
    status: 'completed',
    reach: 9870,
    clicks: 1245,
    conversions: 89,
    createdAt: new Date('2024-07-30'),
  },
];