import { Campaign, WhatsAppTemplate } from '@/types';

export const mockCampaigns: Campaign[] = [
  {
    id: '1',
    name: 'Black Friday 2024',
    type: 'email',
    status: 'active',
    reach: 15420,
    clicks: 2341,
    conversions: 187,
    createdAt: new Date('2024-09-15'),
  },
  {
    id: '2',
    name: 'Nuevo iPhone 15 - WhatsApp',
    type: 'whatsapp',
    status: 'completed',
    reach: 8750,
    clicks: 1876,
    conversions: 94,
    createdAt: new Date('2024-09-10'),
  },
  {
    id: '3',
    name: 'Descuento Estudiantes',
    type: 'in-web',
    status: 'active',
    reach: 3421,
    clicks: 567,
    conversions: 78,
    createdAt: new Date('2024-09-20'),
  },
  {
    id: '4',
    name: 'SMS Back to School',
    type: 'sms',
    status: 'paused',
    reach: 12300,
    clicks: 1890,
    conversions: 145,
    createdAt: new Date('2024-08-25'),
  },
  {
    id: '5',
    name: 'Newsletter Semanal',
    type: 'email',
    status: 'active',
    reach: 25600,
    clicks: 3200,
    conversions: 256,
    createdAt: new Date('2024-01-01'),
  },
  {
    id: '6',
    name: 'Promoción Gaming',
    type: 'whatsapp',
    status: 'draft',
    reach: 0,
    clicks: 0,
    conversions: 0,
    createdAt: new Date('2024-09-22'),
  },
  {
    id: '7',
    name: 'Pop-up Descuento 10%',
    type: 'in-web',
    status: 'active',
    reach: 18450,
    clicks: 2876,
    conversions: 432,
    createdAt: new Date('2024-08-15'),
  },
  {
    id: '8',
    name: 'Reactivación Clientes',
    type: 'email',
    status: 'completed',
    reach: 9870,
    clicks: 1245,
    conversions: 89,
    createdAt: new Date('2024-07-30'),
  },
];

export const mockWhatsAppTemplates: WhatsAppTemplate[] = [
  {
    id: 'wt1',
    name: 'bienvenida_cliente',
    category: 'MARKETING',
    language: 'es',
    status: 'active',
    header: {
      type: 'IMAGE',
      content: 'https://example.com/welcome.jpg',
    },
    body: 'Hola {{1}}! 🎉 Bienvenido a nuestra tienda. Como regalo de bienvenida, te obsequiamos un {{2}}% de descuento en tu primera compra. Usa el código: {{3}}',
    footer: 'Válido por 30 días',
    buttons: [
      {
        id: 1,
        type: 'URL',
        text: 'Ver productos',
        url: 'https://tienda.com/productos',
      },
      {
        id: 2,
        type: 'QUICK_REPLY',
        text: 'Más información',
      },
    ],
    metrics: {
      sent: 15420,
      delivered: 15200,
      read: 12800,
      clicks: 3420,
      conversions: 892,
      openRate: 84.2,
      ctr: 22.5,
      conversionRate: 5.9,
    },
    lastUsed: new Date('2024-10-28'),
    createdAt: new Date('2024-01-15'),
    updatedAt: new Date('2024-10-28'),
  },
  {
    id: 'wt2',
    name: 'carrito_abandonado',
    category: 'MARKETING',
    language: 'es',
    status: 'active',
    header: {
      type: 'TEXT',
      content: '¡No te quedes sin tus productos!',
    },
    body: 'Hola {{1}}, notamos que dejaste productos en tu carrito:\n\n{{2}}\n\nCompleta tu compra ahora y obtén envío gratis 🚚',
    footer: 'Oferta válida por 24 horas',
    buttons: [
      {
        id: 1,
        type: 'URL',
        text: 'Completar compra',
        url: 'https://tienda.com/checkout',
      },
    ],
    metrics: {
      sent: 8750,
      delivered: 8600,
      read: 7200,
      clicks: 2150,
      conversions: 645,
      openRate: 83.7,
      ctr: 25.0,
      conversionRate: 7.5,
    },
    lastUsed: new Date('2024-10-27'),
    createdAt: new Date('2024-02-20'),
    updatedAt: new Date('2024-10-27'),
  },
  {
    id: 'wt3',
    name: 'confirmacion_pedido',
    category: 'UTILITY',
    language: 'es',
    status: 'active',
    header: {
      type: 'NONE',
      content: '',
    },
    body: '✅ Tu pedido #{{1}} ha sido confirmado.\n\n📦 Productos:\n{{2}}\n\n💰 Total: {{3}}\n\n🚚 Fecha estimada de entrega: {{4}}',
    footer: 'Gracias por tu compra',
    buttons: [
      {
        id: 1,
        type: 'URL',
        text: 'Rastrear pedido',
        url: 'https://tienda.com/tracking/{{1}}',
      },
      {
        id: 2,
        type: 'PHONE_NUMBER',
        text: 'Atención al cliente',
        phoneNumber: '+573001234567',
      },
    ],
    metrics: {
      sent: 45320,
      delivered: 45100,
      read: 43200,
      clicks: 15420,
      conversions: 0,
      openRate: 95.8,
      ctr: 34.2,
      conversionRate: 0,
    },
    lastUsed: new Date('2024-10-29'),
    createdAt: new Date('2024-01-10'),
    updatedAt: new Date('2024-10-29'),
  },
  {
    id: 'wt4',
    name: 'codigo_verificacion',
    category: 'AUTHENTICATION',
    language: 'es',
    status: 'active',
    header: {
      type: 'NONE',
      content: '',
    },
    body: 'Tu código de verificación es: {{1}}\n\nNo compartas este código con nadie.',
    footer: 'Válido por 10 minutos',
    buttons: [],
    metrics: {
      sent: 128450,
      delivered: 128200,
      read: 127800,
      clicks: 0,
      conversions: 0,
      openRate: 99.7,
      ctr: 0,
      conversionRate: 0,
    },
    lastUsed: new Date('2024-10-29'),
    createdAt: new Date('2024-01-05'),
    updatedAt: new Date('2024-10-29'),
  },
  {
    id: 'wt5',
    name: 'promocion_flash',
    category: 'MARKETING',
    language: 'es',
    status: 'pending',
    header: {
      type: 'VIDEO',
      content: 'https://example.com/promo.mp4',
    },
    body: '⚡ FLASH SALE ⚡\n\n{{1}}, tienes {{2}} horas para aprovechar:\n\n🎯 {{3}}% de descuento en {{4}}\n\nCódigo: {{5}}',
    footer: 'Stock limitado',
    buttons: [
      {
        id: 1,
        type: 'URL',
        text: 'Comprar ahora',
        url: 'https://tienda.com/flash',
      },
    ],
    metrics: {
      sent: 0,
      delivered: 0,
      read: 0,
      clicks: 0,
      conversions: 0,
      openRate: 0,
      ctr: 0,
      conversionRate: 0,
    },
    createdAt: new Date('2024-10-25'),
    updatedAt: new Date('2024-10-25'),
  },
  {
    id: 'wt6',
    name: 'reseña_producto',
    category: 'MARKETING',
    language: 'es',
    status: 'inactive',
    header: {
      type: 'TEXT',
      content: 'Tu opinión es importante',
    },
    body: 'Hola {{1}}, ¿qué te pareció tu {{2}}?\n\nNos encantaría conocer tu experiencia. Deja tu reseña y obtén {{3}} puntos de recompensa.',
    footer: '',
    buttons: [
      {
        id: 1,
        type: 'URL',
        text: 'Dejar reseña',
        url: 'https://tienda.com/review',
      },
      {
        id: 2,
        type: 'QUICK_REPLY',
        text: '⭐⭐⭐⭐⭐',
      },
    ],
    metrics: {
      sent: 3420,
      delivered: 3350,
      read: 2800,
      clicks: 420,
      conversions: 210,
      openRate: 83.6,
      ctr: 15.0,
      conversionRate: 6.3,
    },
    lastUsed: new Date('2024-09-15'),
    createdAt: new Date('2024-03-10'),
    updatedAt: new Date('2024-09-15'),
  },
  {
    id: 'wt7',
    name: 'recordatorio_cita',
    category: 'UTILITY',
    language: 'es',
    status: 'rejected',
    header: {
      type: 'LOCATION',
      content: '',
    },
    body: '📅 Recordatorio: Tienes una cita mañana\n\n👤 Cliente: {{1}}\n📍 Sucursal: {{2}}\n🕐 Hora: {{3}}',
    footer: 'Te esperamos',
    buttons: [
      {
        id: 1,
        type: 'QUICK_REPLY',
        text: 'Confirmar',
      },
      {
        id: 2,
        type: 'QUICK_REPLY',
        text: 'Cancelar',
      },
    ],
    metrics: {
      sent: 0,
      delivered: 0,
      read: 0,
      clicks: 0,
      conversions: 0,
      openRate: 0,
      ctr: 0,
      conversionRate: 0,
    },
    createdAt: new Date('2024-08-20'),
    updatedAt: new Date('2024-08-22'),
  },
];